### ISSUE TITLE
GraphQL : Query - how to get more than the 100 first repo or how to get next 100 till the last

### ISSUE THREAD

**Issue by yboujraf** [moollaza/repo-remover#160] opened 2020-09-11 14:22 UTC
Dear @moollaza 

I tried to modify the number of repo returned by the query.

If more than 100, I got an error.

I tried :

```
query($ghLogin:String!){
  user(login:$ghLogin) {
    id
    name
    login
    avatarUrl
    bioHTML
    repositories(last:100, ownerAffiliations: [OWNER, ORGANIZATION_MEMBER, COLLABORATOR]) {
      nodes {
        id
        viewerCanAdminister
        name
        description
        isFork
        isPrivate
        isArchived
        updatedAt
        url
        parent {
          nameWithOwner
          url
        }
        owner {
          login
          url
        }
      }
    }
  }
}
```

I got the last 100 repositories.

But finally, how to get from 100 till 200 ?

Best Regards,
Youssef

**Comment by moollaza** [comment] 2020-09-12 20:33
Duplicate of #138 

@yboujraf the API is limited to returning at most 100 repos per page. To get more than 100 results, we need to implement a check for additional pages of results.

**Comment by moollaza** [comment] 2020-09-12 20:33
@yboujraf the API is limited to returning at most 100 repos per page. To get more than 100 results, we need to implement a check for additional pages of results.

**Closed by moollaza** 2020-09-12 20:33 UTC
